#
#  Configuration file for BitWave Bio
#     https://github.com/BitWaveOrg
#           https://five.bio
#

user_firstname: 'End3rrrr' # Username shown on profile (Required)
userbio: 'Tryin to be streamer' # Profile description (Required)

telegram_login: 'End3rrrr' # Telegram login (Optional)
instagram_login: '_end3rrrr_' # Instagram login (Optional)

profile_theme: 'dark' # Profile style
profile_color: 'rgb(0,0,0)' # Profile border color
