#
#  Configuration file for BitWave Bio
#     https://github.com/BitWaveOrg
#           https://five.bio
#

user_firstname: 'End3rrrr' # Username shown on profile (Required)
userbio: 'Tryin to be streamer' # Profile description (Required)

linkedin_login: 'your_linkedin' # LinkedIn login (Optional)
telegram_login: 'End3rrrr' # Telegram login (Optional)
discords_login: 'your_discord' # DiscordS login (Optional)
steam_login: 'your_steam_customid' # SteamCommunity ID (Optional)
instagram_login: 'your_insta' # Instagram login (Optional)
twitter_login: 'your_twitter' # Twitter login (Optional)
website_url: 'https://your.web.site' # Website url (Optional)
cv_url: 'your_cv_url' # CV URL (Optional)

profile_theme: 'dark' # Profile style
profile_color: 'rgb(0,0,0)' # Profile border color
